-- ============================================================
-- Booking configuration + calendar blocks
-- Run once in Supabase SQL Editor.
--
-- The public booking calendar uses booking_blackouts for exact
-- date/time ranges. The legacy booking_schedule_rules table is no
-- longer read by the website.
-- ============================================================

create table if not exists public.booking_settings (
  id integer primary key default 1 check (id = 1),
  slot_minutes integer not null default 30 check (slot_minutes > 0),
  opening_time time not null default '09:00',
  closing_time time not null default '18:00',
  advance_months integer not null default 3 check (advance_months > 0),
  messages jsonb not null default '{}'::jsonb,
  date_time_text jsonb not null default '{}'::jsonb,
  review_text jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.booking_blackouts (
  id bigint generated by default as identity primary key,
  starts_at timestamp without time zone not null,
  ends_at timestamp without time zone not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint booking_blackouts_range_chk check (ends_at > starts_at)
);

create index if not exists booking_blackouts_start_idx
  on public.booking_blackouts(starts_at);

create index if not exists booking_blackouts_end_idx
  on public.booking_blackouts(ends_at);

-- Keep the legacy table for backwards compatibility with an existing
-- database, but the website and CRM no longer read/write it.
-- It can be dropped later after verifying the new calendar blocks.

create or replace function public.set_booking_settings_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_booking_settings_updated_at
on public.booking_settings;

create trigger trg_booking_settings_updated_at
before update on public.booking_settings
for each row execute function public.set_booking_settings_updated_at();

drop trigger if exists trg_booking_blackouts_updated_at
on public.booking_blackouts;

create trigger trg_booking_blackouts_updated_at
before update on public.booking_blackouts
for each row execute function public.set_booking_settings_updated_at();

-- ============================================================
-- RLS
-- ============================================================

alter table public.booking_settings enable row level security;
alter table public.booking_blackouts enable row level security;

drop policy if exists "public_select_booking_settings"
on public.booking_settings;

create policy "public_select_booking_settings"
on public.booking_settings
for select
to anon, authenticated
using (id = 1);

drop policy if exists "crm_admin_select_booking_settings"
on public.booking_settings;

create policy "crm_admin_select_booking_settings"
on public.booking_settings
for select
to authenticated
using ((select public.is_admin()));

drop policy if exists "crm_admin_insert_booking_settings"
on public.booking_settings;

create policy "crm_admin_insert_booking_settings"
on public.booking_settings
for insert
to authenticated
with check ((select public.is_admin()));

drop policy if exists "crm_admin_update_booking_settings"
on public.booking_settings;

create policy "crm_admin_update_booking_settings"
on public.booking_settings
for update
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "public_select_booking_blackouts"
on public.booking_blackouts;

create policy "public_select_booking_blackouts"
on public.booking_blackouts
for select
to anon, authenticated
using (true);

drop policy if exists "crm_admin_select_booking_blackouts"
on public.booking_blackouts;

create policy "crm_admin_select_booking_blackouts"
on public.booking_blackouts
for select
to authenticated
using ((select public.is_admin()));

drop policy if exists "crm_admin_insert_booking_blackouts"
on public.booking_blackouts;

create policy "crm_admin_insert_booking_blackouts"
on public.booking_blackouts
for insert
to authenticated
with check ((select public.is_admin()));

drop policy if exists "crm_admin_update_booking_blackouts"
on public.booking_blackouts;

create policy "crm_admin_update_booking_blackouts"
on public.booking_blackouts
for update
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "crm_admin_delete_booking_blackouts"
on public.booking_blackouts;

create policy "crm_admin_delete_booking_blackouts"
on public.booking_blackouts
for delete
to authenticated
using ((select public.is_admin()));

-- ============================================================
-- Seed booking settings
-- ============================================================

insert into public.booking_settings (
  id,
  slot_minutes,
  opening_time,
  closing_time,
  advance_months,
  messages,
  date_time_text,
  review_text
)
values (
  1,
  30,
  '09:00',
  '18:00',
  3,
  '{
    "en": {
      "closed": "Closed",
      "booked": "Booked",
      "available": "Available"
    },
    "ar": {
      "closed": "مغلق",
      "booked": "محجوز",
      "available": "متاح"
    }
  }'::jsonb,
  '{
    "back": {"en":"Back","ar":"رجوع"},
    "title": {"en":"When would you like to come?","ar":"متى ترغبين في القدوم؟"},
    "description": {"en":"Pick a date, then choose a start time that fits all your selected services.","ar":"اختاري التاريخ ثم وقت البدء المناسب لجميع الخدمات التي اخترتها."}
  }'::jsonb,
  '{
    "back": {"en":"Back","ar":"رجوع"},
    "title": {"en":"ONE MORE STEP!","ar":"خطوة أخيرة!"},
    "description": {
      "en":"To complete your appointment, please review all details described below. Don''t forget to provide your name and phone and telephone so that we could contact you.",
      "ar":"لإتمام موعدك، يرجى مراجعة جميع التفاصيل الموضحة أدناه. لا تنسَ تزويدنا باسمك ورقم هاتفك حتى نتمكن من التواصل معك."
    },
    "serviceLabel": {"en":"Service:","ar":"الخدمة:"},
    "dateLabel": {"en":"Date:","ar":"التاريخ:"},
    "namePlaceholder": {"en":"Full Name","ar":"الاسم الكامل"},
    "phonePlaceholder": {"en":"Telephone","ar":"رقم الهاتف"},
    "submitButton": {"en":"Book now","ar":"احجز الآن"},
    "submitting": {"en":"Booking...","ar":"جارٍ الحجز..."},
    "successMessage": {"en":"Thanks! We will contact you soon.","ar":"شكراً! سنتواصل معك قريباً."},
    "errorMessage": {"en":"Oops! Something went wrong.","ar":"عذراً! حدث خطأ ما."},
    "voucherLabel": {"en":"Voucher:","ar":"قسيمة:"}
  }'::jsonb
)
on conflict (id) do update set
  slot_minutes = excluded.slot_minutes,
  opening_time = excluded.opening_time,
  closing_time = excluded.closing_time,
  advance_months = excluded.advance_months,
  messages = excluded.messages,
  date_time_text = excluded.date_time_text,
  review_text = excluded.review_text,
  updated_at = now();

-- ============================================================
-- IMPORTANT:
-- Existing rows in booking_schedule_rules are intentionally NOT
-- applied to the new calendar. Recreate any desired closures or
-- blocked periods in CRM > Booking Setup > Closures & blocked times.
--
-- This avoids silently carrying year-less recurring rules into the
-- new year-aware calendar system.
-- ============================================================

-- Verification:
-- select * from public.booking_settings;
-- select * from public.booking_blackouts order by starts_at;
